/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package revisi_kntl;


import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import javax.swing.table.TableModel;
import koneksi.koneksi;
import koneksi.user;



/**
 *
 * @author Faujixx
 */
public class login extends javax.swing.JFrame {
public static String username;
    /**
     * Creates new form login
     */
    public login(String username) {
          
        initComponents();
     this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uss_txt = new javax.swing.JTextField();
        pss_txt = new javax.swing.JPasswordField();
        admintxt_btn1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logintxt_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uss_txt.setBorder(null);
        getContentPane().add(uss_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 262, 290, 50));

        pss_txt.setBorder(null);
        getContentPane().add(pss_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 329, 290, 50));

        admintxt_btn1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        admintxt_btn1.setForeground(new java.awt.Color(51, 51, 255));
        admintxt_btn1.setText("admin");
        admintxt_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admintxt_btn1MouseClicked(evt);
            }
        });
        getContentPane().add(admintxt_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("atau login sebagai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/login btn.png"))); // NOI18N
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        getContentPane().add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jika anda belum register silahkan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        logintxt_btn.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        logintxt_btn.setForeground(new java.awt.Color(51, 51, 255));
        logintxt_btn.setText("register");
        logintxt_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logintxt_btnMouseClicked(evt);
            }
        });
        getContentPane().add(logintxt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/Frame 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admintxt_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admintxt_btn1MouseClicked
        admin_login admin = new admin_login(username);
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_admintxt_btn1MouseClicked

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
  try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM user where username ='"+uss_txt.getText()+"' AND password='"+pss_txt.getText()+"'");
           
            if(res.next()){    
                    JOptionPane.showMessageDialog(null, "berhasil login");
                     user user= new user(res.getString("username"));
                     
                     main_home homepage = new main_home(res.getString("username"));
                    homepage.setVisible(true);
                    dispose();
 
                
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_login_btnMouseClicked

    private void logintxt_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintxt_btnMouseClicked

       register register = new register(username );
      register.setVisible(true);
      dispose();
      
    }//GEN-LAST:event_logintxt_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admintxt_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login_btn;
    private javax.swing.JLabel logintxt_btn;
    private javax.swing.JPasswordField pss_txt;
    private javax.swing.JTextField uss_txt;
    // End of variables declaration//GEN-END:variables
}
