package revisi_kntl;

/**
 *
 * @author Faujixx
 */
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.HeadlessException;
import java.util.HashMap;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.ArrayList;
import java.util.List;

public class status_alat extends javax.swing.JFrame {
private static String username;
    /**
     * Creates new form status_alat
     */
    public status_alat(String username) {
        initComponents();
        this.username = username;
        loadDataToTable();
    }
    private void saveDataToDatabase(String namaAlat, int jumlahAlat, double hargaSewa) {
    try (Connection connection = koneksi.GetConnection();
         PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO alat (Nama_Alat, jumlah_Alat, Harga_sewa) VALUES (?, ?, ?)")) {

        preparedStatement.setString(1, namaAlat);
        preparedStatement.setInt(2, jumlahAlat);
        preparedStatement.setDouble(3, hargaSewa);

        int result = preparedStatement.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan ke dalam database.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Gagal menyimpan data ke dalam database.");
        }

    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}
    
private void loadDataToTable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("id_Hpinjam");
    model.addColumn("Tgl_pinjam");
    model.addColumn("Tenggat_peminjaman");
    model.addColumn("Username");
    model.addColumn("id_Detpinjam");
    model.addColumn("status_peminjaman");
    model.addColumn("id_Detpinjam");
    model.addColumn("Total_alat");
    model.addColumn("jumlah_Alatpinjam");
    model.addColumn("id_alat");

    try (Connection connection = koneksi.GetConnection();
         Statement statement = connection.createStatement();
         ResultSet resultSet = statement.executeQuery("select * from meminjam join detail_peminjaman")) {

        while (resultSet.next()) {
            String id_Hpinjam = resultSet.getString("id_Hpinjam");
            String Tgl_pinjam = resultSet.getString("Tgl_pinjam");
            String Tenggat_peminjaman = resultSet.getString("Tenggat_peminjaman");
            String Username = resultSet.getString("Username");
            String id_Detpinjam = resultSet.getString("id_Detpinjam");
            String status_peminjaman = resultSet.getString("status_peminjaman");
            String Total_alat = resultSet.getString("Total_alat");
            String jumlah_Alatpinjam = resultSet.getString("jumlah_Alatpinjam");
            String id_alat = resultSet.getString("id_alat");

            model.addRow(new Object[]{id_Hpinjam, Tgl_pinjam, Tenggat_peminjaman, Username, id_Detpinjam, status_peminjaman, id_Detpinjam, Total_alat, jumlah_Alatpinjam, id_alat});
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error loading data from database: " + e.getMessage());
    }

    jTable1.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/Vector (1).png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 28, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/Vector.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 27, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/mingcute_back-2-fill.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 27, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 600, 270));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(34, 87, 122));
        rSMaterialButtonRectangle1.setText("print");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 200, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 570, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/Group 17.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png_ui/Frame 22.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
admin_main admin = new admin_main(username);
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
       admin_main admin = new admin_main(username);
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
pertanian_main main =new pertanian_main(username);       
main.setVisible(true);
dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        try{
            String reportPath = "src/Report/data_sewa.jasper";
            Connection connection = koneksi.GetConnection();
            HashMap<String, Object> parameters=new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath, parameters, connection);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error displaying report"+ e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String searchInput = jTextField1.getText().trim();

    // Check if the search input is not empty
    if (!searchInput.isEmpty()) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(tableModel);
        jTable1.setRowSorter(rowSorter);

        // Specify the column index you want to search in (adjust as needed)
        int columnIndexToSearch = 1; // Assuming you want to search in the second column (index 1)

        // Set the RowFilter to perform case-insensitive search
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchInput, columnIndexToSearch));
    } else {
        // If search input is empty, reset the row sorter to show all rows
        jTable1.setRowSorter(null);
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
// Get the search input from jTextField1
    String searchInput = jTextField1.getText().trim();

    // Check if the search input is not empty
    if (!searchInput.isEmpty()) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(tableModel);
        jTable1.setRowSorter(rowSorter);

        List<RowFilter<Object, Object>> filters = new ArrayList<>();

        // Tambahkan filter untuk setiap kolom (mencakup seluruh kolom)
        for (int i = 0; i < tableModel.getColumnCount(); i++) {
            filters.add(RowFilter.regexFilter("(?i)" + searchInput, i));
        }

        // Gabungkan semua filter menggunakan OR (||)
        RowFilter<Object, Object> combinedFilter = RowFilter.orFilter(filters);

        // Terapkan filter ke model tabel
        rowSorter.setRowFilter(combinedFilter);
    } else {
        // If search input is empty, reset the row sorter to show all rows
        jTable1.setRowSorter(null);
    }
    }//GEN-LAST:event_jLabel2MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(status_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(status_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(status_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(status_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new status_alat(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logout;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    // End of variables declaration//GEN-END:variables
}
